version: "2"
services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/conf.d/:/etc/nginx/conf.d
      - ./configs/vhost.d/:/etc/nginx/vhost.d
      - ./configs/certs/:/etc/nginx/certs
      - ./configs/htpasswd/:/etc/nginx/htpasswd

      - ./logs/:/var/log/nginx
      - ./projects/:/var/www/html

  dockergen:
    container_name: dockergen
    restart: always
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./configs/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  db_mysql:
    container_name: db_mysql
    restart: always
    image: mysql:8.0
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
         - PMA_ARBITRARY=1
        restart: always
        ports:
         - 8081:80
        environment:
          PMA_HOST: db_mysql
volumes:
  nginx:
    external: true
